#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["airproject.web/airproject.web.csproj", "airproject.web/"]
COPY ["airproject.domain/airproject.domain.csproj", "airproject.domain/"]
COPY ["airproject.providers.openair/airproject.providers.openair.csproj", "airproject.providers.openair/"]
RUN dotnet restore "airproject.web/airproject.web.csproj"
COPY . .
WORKDIR "/src/airproject.web"
RUN dotnet build "airproject.web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "airproject.web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "airproject.web.dll"]