version: '3.3'

services:
  seq:
    image: datalust/seq
    ports:
    - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    environment:
      - Seq__ServerUrl=http://seq